### ISSUE TITLE
why is this 4 months old?

### ISSUE THREAD

**Issue by ShawnTalbert** [cmichaelgraham/aurelia-typescript-atom#8]
Is there somewhere that has typescript definitions of aurelia kept up to date?

**Comment by cmichaelgraham** [comment]
have a look [here](https://github.com/cmichaelgraham/aurelia-amd-bundler/tree/master/typings/aurelia)

had to do some manual edits to the .d.ts files

they are now automatically generated, but prior to the 25 PRs i did last week, when aurelia releases the repos, no typescript compilation was done, so errors were slipping through.

that should be fixed in the next couple of days and then i'll update the repo :+1:

**Comment by ShawnTalbert** [comment]
Many thanks! relieved to know this wasn't an abandoned effort. Might I ask how these are autogenerated?

**Comment by cmichaelgraham** [comment]
@ironside - sure - the types are added to the `.js` files in each aurelia repo.  then [babel-dts-generator](https://github.com/YoloDev/babel-dts-generator) is used (during `gulp build` for the repo) to create the `.d.ts` files

**Comment by ShawnTalbert** [comment]
Thanks. Keep up the good types!
